include_guard(GLOBAL)

set(PROCESSEDFOLDER_DIR ${CMAKE_CURRENT_LIST_DIR})

file(GLOB PROCESSEDFOLDER_SOURCES
	${PROCESSEDFOLDER_DIR}/src/*.hpp
	${PROCESSEDFOLDER_DIR}/src/*.cpp)

if(EXISTS "${PROCESSEDFOLDER_DIR}/src/LapisGis/LapisGis.cmake")
	include("${PROCESSEDFOLDER_DIR}/src/LapisGis/LapisGis.cmake")
else()
	include("${PROCESSEDFOLDER_DIR}/../LapisGis/LapisGis.cmake")
endif()

set(PROCESSEDFOLDER_EXTERNAL_INCLUDES
	${LAPISGIS_INCLUDES}
	)

set(PROCESSEDFOLDER_EXTERNAL_LINKS
	${LAPISGIS_LINKS}
	)

add_library(ProcessedFolder STATIC ${PROCESSEDFOLDER_SOURCES})
target_include_directories(ProcessedFolder PRIVATE ${PROCESSEDFOLDER_EXTERNAL_INCLUDES})
target_precompile_headers(ProcessedFolder PRIVATE ${PROCESSEDFOLDER_DIR}/src/ProcessedFolder_pch.hpp)
	
set(PROCESSEDFOLDER_INCLUDES
	${PROCESSEDFOLDER_EXTERNAL_INCLUDES}
	${PROCESSEDFOLDER_DIR}/src
	)
set(PROCESSEDFOLDER_LINKS
	${PROCESSEDFOLDER_EXTERNAL_LINKS}
	ProcessedFolder
	)
