include_guard(GLOBAL)

set(PROCESSEDFOLDER_DIR ${CMAKE_CURRENT_LIST_DIR})

file(GLOB PROCESSEDFOLDER_SOURCES
	${PROCESSEDFOLDER_DIR}/src/*.hpp
	${PROCESSEDFOLDER_DIR}/src/*.cpp)

include("${PROCESSEDFOLDER_DIR}/src/LapisApi/lapisapi.cmake")

set(PROCESSEDFOLDER_EXTERNAL_INCLUDES
	${LAPISAPI_INCLUDES}
	)

set(PROCESSEDFOLDER_EXTERNAL_LINKS
	${LAPISAPI_LINKS}
	)

add_library(ProcessedFolder STATIC ${PROCESSEDFOLDER_SOURCES})
target_include_directories(ProcessedFolder PRIVATE ${PROCESSEDFOLDER_EXTERNAL_INCLUDES})
target_precompile_headers(ProcessedFolder PRIVATE ${PROCESSEDFOLDER_DIR}/src/ProcessedFolder_pch.hpp)
	
set(PROCESSEDFOLDER_INCLUDES
	${LAPISAPI_EXTERNAL_INCLUDES}
	${PROCESSEDFOLDER_DIR}/src
	)
set(PROCESSEDFOLDER_LINKS
	${PROCESSEDFOLDER_EXTERNAL_LINKS}
	ProcessedFolder
	)
